//! Vault identifier generation (spec §13 item 5).
//!
//! For cloud vaults `vault_id` = a random UUIDv4 (16 bytes), generated by the
//! client. The server-side ownership rule (reject-if-exists, owner =
//! genesis-pubkey) lives on the server (outside this repository). Local vaults
//! may still use arbitrary bytes (D2): this function is the recommended source
//! of ids for cloud, it is NOT forced on `Vault::create`.

/// A new random `vault_id` as 16 bytes of UUIDv4 (RFC 4122).
///
/// The version/variant bits are set by the `uuid` crate (no custom crypto is
/// written); entropy comes from the system CSPRNG. Returns "raw" bytes usable as
/// a `vault_id` in `Vault::create`/cloud API.
pub fn new_vault_id() -> Vec<u8> {
    uuid::Uuid::new_v4().as_bytes().to_vec()
}
